### ISSUE TITLE
Error checking disk space when running ethd update

### ISSUE THREAD

**Issue by jimmygchen** [eth-educators/eth-docker#1217]
I just ran `ethd update` and received a panic from docker and bash failure in `check_disk_space`.

1. It looks like this command is giving me the panic
```
__docker_dir=$(docker system info --format '{{.DockerRootDir}}')
```
if I run the above command, it gives me the same panic as below. But it works if I run it with `sudo`.

2. and this command returns multiple numbers for me, causing the compare expression to fail:
```
__free_space=$(df -P ${__docker_dir} | awk '/[0-9]%/{print $(NF-2)}')
```

## Environment

OS: Ubuntu 22.04.2 LTS
Docker: 20.10.12

## Full error

```
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc0004bd2d8)
	/usr/lib/go-1.17/src/text/template/exec.go:169 +0x145
panic({0x562ad3996aa0, 0x562ad3c523d8})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
reflect.Value.FieldByIndex({0x562ad3b1a080, 0xc000122280, 0x0}, {0xc000057220, 0x2, 0x562ad3996aa0})
	/usr/lib/go-1.17/src/reflect/value.go:1224 +0x1e7
text/template.(*state).evalField(0xc0004bd308, {0x562ad3b1a080, 0xc000122280, 0x562ad28b800a}, {0x7fff4d45d6bb, 0xd}, {0x562ad3cbd2b0, 0xc00011ecf0}, {0xc00043ae10, 0x1, ...}, ...)
	/usr/lib/go-1.17/src/text/template/exec.go:616 +0x450
text/template.(*state).evalFieldChain(0x7fff4d45d6ba, {0x562ad3b1a080, 0xc000122280, 0x14}, {0x562ad3b1a080, 0xc000122280, 0x0}, {0x562ad3cbd2b0, 0xc00011ecf0}, {0xc00043ae00, ...}, ...)
	/usr/lib/go-1.17/src/text/template/exec.go:569 +0x1eb
text/template.(*state).evalFieldNode(0x203000, {0x562ad3b1a080, 0xc000122280, 0xc000743380}, 0xc0004bd030, {0xc00043ae10, 0x0, 0x1}, {0x562ad3a1e980, 0x562ad4be6840, ...})
	/usr/lib/go-1.17/src/text/template/exec.go:533 +0xce
text/template.(*state).evalCommand(0xc0004bd308, {0x562ad3b1a080, 0xc000122280, 0x203000}, 0xc000743450, {0x562ad3a1e980, 0x562ad4be6840, 0x0})
	/usr/lib/go-1.17/src/text/template/exec.go:461 +0x296
text/template.(*state).evalPipeline(0xc0004bd308, {0x562ad3b1a080, 0xc000122280, 0xc00011ed50}, 0xc0001ab980)
	/usr/lib/go-1.17/src/text/template/exec.go:435 +0x145
text/template.(*state).walk(0xc0004bd308, {0x562ad3b1a080, 0xc000122280, 0x10000c000122240}, {0x562ad3cbd0b8, 0xc00011ed20})
	/usr/lib/go-1.17/src/text/template/exec.go:254 +0x1f6
text/template.(*state).walk(0xc0004bd308, {0x562ad3b1a080, 0xc000122280, 0x0}, {0x562ad3cbd388, 0xc00011ec90})
	/usr/lib/go-1.17/src/text/template/exec.go:263 +0x37d
text/template.(*Template).execute(0xc000122240, {0x562ad3c6d4a0, 0xc00029b740}, {0x562ad3b1a080, 0xc000122280})
	/usr/lib/go-1.17/src/text/template/exec.go:217 +0x2d8
text/template.(*Template).Execute(...)
	/usr/lib/go-1.17/src/text/template/exec.go:200
github.com/docker/cli/cli/command/system.formatInfo({0x562ad3ce9778, 0xc00050e5b0}, {0x0, {0xc00043adb0, 0x1, 0x1}, 0xc00004e4b0, {0x0, 0x0, 0x0}}, ...)
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/cli/command/system/info.go:511 +0x1a8
github.com/docker/cli/cli/command/system.runInfo(0xc0004bdcd0, {0x562ad3ce9778, 0xc00050e5b0}, 0xc00043a540)
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/cli/command/system/info.go:88 +0x47d
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc000496580, {0xc0001d0c40, 0x0, 0x2})
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/cli/command/system/info.go:54 +0x25
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000496580, {0xc0001e45a0, 0x2, 0x2})
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000236580)
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0x0)
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1ce
main.main()
	/build/docker.io-E1puQZ/docker.io-20.10.12/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:298 +0x97
/home/ethereum/goerli/eth-docker-goerli/ethd: line 282: [[: 3244948
324004208
16246704
5116
16246704
517884
3248440
3249280: syntax error in expression (error token is "324004208
16246704
5116
16246704
517884
3248440
3249280")
/home/ethereum/goerli/eth-docker-goerli/ethd: line 291: [[: 3244948
324004208
16246704
5116
16246704
517884
3248440
3249280: syntax error in expression (error token is "324004208
16246704
5116
16246704
517884
3248440
3249280")
```

**Comment by yorickdowne** [comment]
Thank you! I think we both are fixing it the same way.

**Comment by yorickdowne** [comment]
Should be fixed with the latest update.
