### ISSUE TITLE
Nethermind won't start if `AUTOPRUNE_NM=false`

### ISSUE THREAD

**Issue by iSOcH** [eth-educators/eth-docker#1298]
It will fail with this output

```
eth-docker-execution-1  | Using pruning parameters:
eth-docker-execution-1  | --Pruning.FullPruningMaxDegreeOfParallelism=6 --Pruning.Mode=Full
eth-docker-execution-1  | 2023-04-14 07-32-00.6712|Nethermind starting initialization.
eth-docker-execution-1  | 2023-04-14 07-32-00.7081|Loading embedded plugins
eth-docker-execution-1  | 2023-04-14 07-32-00.7083|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7083|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7083|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7083|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7083|  Found plugin type Nethermind.Hive.HivePlugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7083|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7196|Loading 10 assemblies from /nethermind/plugins
eth-docker-execution-1  | 2023-04-14 07-32-00.7197|Loading assembly Nethermind.Api
eth-docker-execution-1  | 2023-04-14 07-32-00.7217|Loading assembly Nethermind.JsonRpc.TraceStore
eth-docker-execution-1  | 2023-04-14 07-32-00.7246|  Found plugin type Nethermind.JsonRpc.TraceStore
eth-docker-execution-1  | 2023-04-14 07-32-00.7246|Loading assembly Nethermind.EthStats
eth-docker-execution-1  | 2023-04-14 07-32-00.7250|  Found plugin type Nethermind.EthStats
eth-docker-execution-1  | 2023-04-14 07-32-00.7251|Loading assembly Nethermind.Consensus.AuRa
eth-docker-execution-1  | 2023-04-14 07-32-00.7278|Loading assembly Nethermind.HealthChecks
eth-docker-execution-1  | 2023-04-14 07-32-00.7286|  Found plugin type Nethermind.HealthChecks
eth-docker-execution-1  | 2023-04-14 07-32-00.7286|Loading assembly Nethermind.Init
eth-docker-execution-1  | 2023-04-14 07-32-00.7290|Loading assembly Nethermind.Merge.Plugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7313|  Found plugin type Nethermind.Merge.Plugin
eth-docker-execution-1  | 2023-04-14 07-32-00.7313|Loading assembly Nethermind.AccountAbstraction
eth-docker-execution-1  | 2023-04-14 07-32-00.7336|  Found plugin type Nethermind.AccountAbstraction
eth-docker-execution-1  | 2023-04-14 07-32-00.7336|Loading assembly Nethermind.Merge.AuRa
eth-docker-execution-1  | 2023-04-14 07-32-00.7339|  Found plugin type Nethermind.Merge.AuRa
eth-docker-execution-1  | 2023-04-14 07-32-00.7339|Loading assembly Nethermind.Mev
eth-docker-execution-1  | 2023-04-14 07-32-00.7350|  Found plugin type Nethermind.Mev
eth-docker-execution-1  | Specify --help for a list of available options and commands.
eth-docker-execution-1  | 2023-04-14 07:32:01.1721|Failure Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value '6' for option 'Pruning.FullPruningMaxDegreeOfParallelism'
eth-docker-execution-1  |    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
eth-docker-execution-1  |    at Nethermind.Runner.Program.Run(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 226
eth-docker-execution-1  |    at Nethermind.Runner.Program.Main(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 73
```

Culprit is on https://github.com/eth-educators/eth-docker/blob/main/nethermind/docker-entrypoint.sh#L63. When autoprune is true, the problematic config in the variable will be overwritten.

Additional topic: Should we not always use `Pruning.Mode=Hybrid`? Without in-memory pruning enabled (part of Hybrid) the db will grow much faster.

**Comment by yorickdowne** [comment]
I changed this to `Full` as per the recommendations of the Nethermind team. Full Pruning still has some quirks. Ultimately, it should be replaced "this year" by pbss.

Let me see what's going on with the Parallelism. Thanks for the report!

**Comment by yorickdowne** [comment]
I can't reproduce this. Do you have a custom version of Nethermind in the targets in `.env` maybe?

**Comment by iSOcH** [comment]
Oh, I see. I also had
```
      - --Pruning.FullPruningMaxDegreeOfParallelism
      - "2"
```
in my `services.execution.entrypoint`.  weird that it then complained about the value which came from `entrypoint.sh`, but I guess it's just not handling the same flag multiple times nicely.

anyway, nothing wrong in this repo. sorry for the noise

**Comment by yorickdowne** [comment]
Quick note that you likely did not need to modify nethermind.yml, as `EL_EXTRAS` exists
