### ISSUE TITLE
Teku crashes (json.lock already in use)

### ISSUE THREAD

**Issue by luisnaranjo733** [eth-educators/eth-docker#400]
I'm running Besu/Teku in execution, consensus, and validator mode
Teku seems to crash pretty immediately.

I've tried running ./ethd terminate, then re-configuring and starting again (same result).

```
bash
Attaching to eth-docker_consensus_1
consensus_1       | 2022-01-24 02:18:36,387 main INFO Setting logging level to INFO
consensus_1       | 2022-01-24 02:18:37,330 main INFO Configuring logging for destination: console
consensus_1       | 2022-01-24 02:18:37,330 main INFO Logging includes events: true
consensus_1       | 2022-01-24 02:18:37,331 main INFO Logging includes validator duties: true
consensus_1       | 2022-01-24 02:18:37,337 main INFO Logging includes color: true
consensus_1       | 2022-01-24 02:18:37,363 main INFO Include P2P warnings set to: false
consensus_1       | 2022-01-24 02:18:37.365 INFO  - Teku version: teku/v22.1.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
consensus_1       | 2022-01-24 02:18:37.376 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
consensus_1       | 2022-01-24 02:18:37.841 INFO  - validator-api-enabled is false, not starting rest api.
consensus_1       | 2022-01-24 02:18:37.927 INFO  - Using default implementation for ThreadExecutor
consensus_1       | 2022-01-24 02:18:37.930 INFO  - Job execution threads will use class loader of thread: main
consensus_1       | 2022-01-24 02:18:37.989 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
consensus_1       | 2022-01-24 02:18:37.991 INFO  - Quartz Scheduler v.2.3.2 created.
consensus_1       | 2022-01-24 02:18:37.992 INFO  - RAMJobStore initialized.
consensus_1       | 2022-01-24 02:18:37.993 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
consensus_1       |   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
consensus_1       |   NOT STARTED.
consensus_1       |   Currently in standby mode.
consensus_1       |   Number of jobs executed: 0
consensus_1       |   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
consensus_1       |   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
consensus_1       |
consensus_1       | 2022-01-24 02:18:37.993 INFO  - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
consensus_1       | 2022-01-24 02:18:37.993 INFO  - Quartz scheduler version: 2.3.2
consensus_1       | 2022-01-24 02:18:38.158 INFO  - Storing beacon chain data in: /var/lib/teku/beacon
consensus_1       | 2022-01-24 02:18:38.169 INFO  - Using optimized BLST library
consensus_1       | 2022-01-24 02:18:38.182 INFO  - Starting metrics http service on 0.0.0.0:8008
consensus_1       | 2022-01-24 02:18:38.190 INFO  - BLS: loaded BLST library
consensus_1       | 2022-01-24 02:18:38.202 INFO  - Loading 1 validator keys...
consensus_1       | 2022-01-24 02:18:38.510 INFO  - Beacon data directory set to: /var/lib/teku/beacon
consensus_1       | 2022-01-24 02:18:38.520 INFO  - Metrics service started and listening on 8008:8008
consensus_1       | 2022-01-24 02:18:38.626 INFO  - Created leveldb_tree Hot and Finalized database (leveldb-tree) at /var/lib/teku/beacon/db
consensus_1       | 2022-01-24 02:18:38.706 INFO  - Using execution engine at http://execution:8545
consensus_1       | 2022-01-24 02:18:38.756 INFO  - Initializing storage
consensus_1       | 2022-01-24 02:18:38.760 INFO  - Storage initialization complete
consensus_1       | 2022-01-24 02:18:38.761 INFO  - Loading initial state from https://github.com/eth-clients/merge-testnets/raw/3d07b2914747c4a8bd847a27c272e048cb2d29d8/kintsugi/genesis.ssz
consensus_1       | 2022-01-24 02:18:42.835 INFO  - Loaded initial state at epoch 0 (state root = 0x01e136a24f58dfa0c8735afdc1ccada58d286ae4e15cb26327d97f040fd8f36b, block root = 0x3bed1de741643a0c616440e7a999fc3dfbe74ba6d5c55a622dc19278e02cc771, block slot = 0).
consensus_1       | 2022-01-24 02:18:42.902 INFO  - Genesis Event ***
consensus_1       | Genesis state root: 0x01e136a24f58dfa0c8735afdc1ccada58d286ae4e15cb26327d97f040fd8f36b
consensus_1       | Genesis block root: 0x3bed1de741643a0c616440e7a999fc3dfbe74ba6d5c55a622dc19278e02cc771
consensus_1       | Genesis time: 2021-12-16 13:05:00 GMT
consensus_1       | 2022-01-24 02:18:44.609 INFO  - Generated new p2p private key and storing in: generated-node-key
consensus_1       | 2022-01-24 02:18:45.096 INFO  - PreGenesis Local ENR: enr:-KG4QL4WQJ8olI2EQQp0TBD6KW9XQePAX0Hr1G7yMI-XSpitKUQ2tBoivX1ASlTveUxoOXlsXpj7fKWDJ6GsZ-2x1xYChGV0aDKQmCTRN2AAAGn__________4JpZIJ2NIJpcIQUbaj6iXNlY3AyNTZrMaECfG9Kq9me_TPIBTBMUBtN1lV-Snh7YpSs-Tcbedik6aaDdGNwgiMog3VkcIIjKA
consensus_1       | 2022-01-24 02:18:45.112 INFO  - Using multipeer sync
consensus_1       | 2022-01-24 02:18:45.315 WARN  - JDK15 and Kotlin 1.5 break reflection in different ways - the OpenAPI plugin will not work properly. Please visit https://github.com/tipsy/javalin/issues/1193 if you want to help fix this issue.
consensus_1       | 2022-01-24 02:18:45.352 INFO  - Logging initialized @11173ms to org.eclipse.jetty.util.log.Slf4jLog
consensus_1       | 2022-01-24 02:18:45.642 INFO  - The latest finalized checkpoint at epoch 0 fell outside of the weak subjectivity period after epoch 1157, which is prior to the current epoch 8674.
consensus_1       | 2022-01-24 02:18:45.643 INFO  - The latest finalized checkpoint at epoch 0 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
consensus_1       | 2022-01-24 02:18:45.692 INFO  - Starting libp2p network...
consensus_1       | 2022-01-24 02:18:45.709 INFO  - Starting discovery server on UDP port 9000
consensus_1       | 2022-01-24 02:18:45.711 INFO  - Listening for connections on: /ip4/20.109.168.250/tcp/9000/p2p/16Uiu2HAm3oQxiapCdorTp8C6ceWoHM9SnPzzCmuRcGgb2muMSmUq
consensus_1       | 2022-01-24 02:18:45.727 INFO  - Monitor has started. Waiting MERGE fork activation. Polling every PT14S
consensus_1       | 2022-01-24 02:18:45.728 INFO  - Starting Javalin ...
consensus_1       | 2022-01-24 02:18:45.753 INFO  - UDP discovery client started
consensus_1       | 2022-01-24 02:18:45.782 INFO  - You are running Javalin 4.1.1 (released October 10, 2021. Your Javalin version is 105 days old. Consider upgrading!).
consensus_1       | 2022-01-24 02:18:45.886 INFO  - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 17.0.1+12
consensus_1       | 2022-01-24 02:18:45.954 INFO  - Local ENR: enr:-KG4QC1RKecSbmiAwVRdodf4rR744WhLTHcvN1jXupWYQz77SjW9_Aw115xncP4uvl3tpGUCEwFYG_hm3b0RJyZz2MkDhGV0aDKQ7nHpc2IAAHH__________4JpZIJ2NIJpcIQUbaj6iXNlY3AyNTZrMaECfG9Kq9me_TPIBTBMUBtN1lV-Snh7YpSs-Tcbedik6aaDdGNwgiMog3VkcIIjKA
consensus_1       | 2022-01-24 02:18:46.105 INFO  - Started ServerConnector@246bc748{HTTP/1.1, (http/1.1)}{0.0.0.0:5052}
consensus_1       | 2022-01-24 02:18:46.105 INFO  - Started @11928ms
consensus_1       | 2022-01-24 02:18:46.106 INFO  - Listening on http://localhost:5052/
consensus_1       | 2022-01-24 02:18:46.106 INFO  - Javalin started in 378ms \o/
consensus_1       | 2022-01-24 02:18:46.110 FATAL - Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       | tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.keystoreInUseException(KeystoreLocker.java:85) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.attemptReplaceStaleLockFile(KeystoreLocker.java:68) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.lockKeystore(KeystoreLocker.java:43) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.loadBLSPrivateKey(LocalValidatorSource.java:267) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.createSigner(LocalValidatorSource.java:254) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource$SlashingProtectedValidatorProvider.createSigner(SlashingProtectedValidatorSource.java:92) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.MultithreadedValidatorLoader.lambda$loadValidators$0(MultithreadedValidatorLoader.java:64) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
consensus_1       | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
consensus_1       | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
consensus_1       | at java.lang.Thread.run(Unknown Source) ~[?:?]
consensus_1       | Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       |
consensus_1       | To display full help:
consensus_1       | teku [COMMAND] --help
consensus_1       | 2022-01-24 02:18:51,478 main INFO Setting logging level to INFO
consensus_1       | 2022-01-24 02:18:52,631 main INFO Configuring logging for destination: console
consensus_1       | 2022-01-24 02:18:52,636 main INFO Logging includes events: true
consensus_1       | 2022-01-24 02:18:52,636 main INFO Logging includes validator duties: true
consensus_1       | 2022-01-24 02:18:52,636 main INFO Logging includes color: true
consensus_1       | 2022-01-24 02:18:52,668 main INFO Include P2P warnings set to: false
consensus_1       | 2022-01-24 02:18:52.670 INFO  - Teku version: teku/v22.1.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
consensus_1       | 2022-01-24 02:18:52.674 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
consensus_1       | 2022-01-24 02:18:53.246 INFO  - validator-api-enabled is false, not starting rest api.
consensus_1       | 2022-01-24 02:18:53.362 INFO  - Using default implementation for ThreadExecutor
consensus_1       | 2022-01-24 02:18:53.369 INFO  - Job execution threads will use class loader of thread: main
consensus_1       | 2022-01-24 02:18:53.453 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
consensus_1       | 2022-01-24 02:18:53.453 INFO  - Quartz Scheduler v.2.3.2 created.
consensus_1       | 2022-01-24 02:18:53.454 INFO  - RAMJobStore initialized.
consensus_1       | 2022-01-24 02:18:53.454 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
consensus_1       |   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
consensus_1       |   NOT STARTED.
consensus_1       |   Currently in standby mode.
consensus_1       |   Number of jobs executed: 0
consensus_1       |   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
consensus_1       |   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
consensus_1       |
consensus_1       | 2022-01-24 02:18:53.455 INFO  - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
consensus_1       | 2022-01-24 02:18:53.455 INFO  - Quartz scheduler version: 2.3.2
consensus_1       | 2022-01-24 02:18:53.565 INFO  - Using optimized BLST library
consensus_1       | 2022-01-24 02:18:53.574 INFO  - BLS: loaded BLST library
consensus_1       | 2022-01-24 02:18:53.594 INFO  - Storing beacon chain data in: /var/lib/teku/beacon
consensus_1       | 2022-01-24 02:18:53.594 INFO  - Starting metrics http service on 0.0.0.0:8008
consensus_1       | 2022-01-24 02:18:53.596 INFO  - Loading 1 validator keys...
consensus_1       | 2022-01-24 02:18:53.892 INFO  - Metrics service started and listening on 8008:8008
consensus_1       | 2022-01-24 02:18:53.895 INFO  - Beacon data directory set to: /var/lib/teku/beacon
consensus_1       | 2022-01-24 02:18:53.966 INFO  - Created leveldb_tree Hot and Finalized database (leveldb-tree) at /var/lib/teku/beacon/db
consensus_1       | 2022-01-24 02:18:54.037 INFO  - Using execution engine at http://execution:8545
consensus_1       | 2022-01-24 02:18:54.087 INFO  - Initializing storage
consensus_1       | 2022-01-24 02:18:56.621 INFO  - Storage initialization complete
consensus_1       | 2022-01-24 02:18:57.692 INFO  - Loading generated p2p private key from: generated-node-key
consensus_1       | 2022-01-24 02:18:58.285 INFO  - PreGenesis Local ENR: enr:-KG4QM6ovWK403UhV216YhgmcluN9NqIgdtkBMByJ-mFJkPLc1Rvs79NSjClGx74HZQzv0e_uAjjjJQIcFoh4adU228FhGV0aDKQmCTRN2AAAGn__________4JpZIJ2NIJpcIQUbaj6iXNlY3AyNTZrMaECfG9Kq9me_TPIBTBMUBtN1lV-Snh7YpSs-Tcbedik6aaDdGNwgiMog3VkcIIjKA
consensus_1       | 2022-01-24 02:18:58.291 INFO  - Using multipeer sync
consensus_1       | 2022-01-24 02:18:58.432 WARN  - JDK15 and Kotlin 1.5 break reflection in different ways - the OpenAPI plugin will not work properly. Please visit https://github.com/tipsy/javalin/issues/1193 if you want to help fix this issue.
consensus_1       | 2022-01-24 02:18:58.476 INFO  - Logging initialized @10279ms to org.eclipse.jetty.util.log.Slf4jLog
consensus_1       | 2022-01-24 02:18:58.665 INFO  - The latest finalized checkpoint at epoch 0 fell outside of the weak subjectivity period after epoch 1157, which is prior to the current epoch 8674.
consensus_1       | 2022-01-24 02:18:58.665 INFO  - The latest finalized checkpoint at epoch 0 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
consensus_1       | 2022-01-24 02:18:58.713 INFO  - Starting libp2p network...
consensus_1       | 2022-01-24 02:18:58.724 INFO  - Listening for connections on: /ip4/20.109.168.250/tcp/9000/p2p/16Uiu2HAm3oQxiapCdorTp8C6ceWoHM9SnPzzCmuRcGgb2muMSmUq
consensus_1       | 2022-01-24 02:18:58.729 INFO  - Starting discovery server on UDP port 9000
consensus_1       | 2022-01-24 02:18:58.750 INFO  - Monitor has started. Waiting MERGE fork activation. Polling every PT14S
consensus_1       | 2022-01-24 02:18:58.763 INFO  - UDP discovery client started
consensus_1       | 2022-01-24 02:18:58.764 INFO  - Starting Javalin ...
consensus_1       | 2022-01-24 02:18:58.797 INFO  - You are running Javalin 4.1.1 (released October 10, 2021. Your Javalin version is 105 days old. Consider upgrading!).
consensus_1       | 2022-01-24 02:18:58.890 INFO  - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 17.0.1+12
consensus_1       | 2022-01-24 02:18:58.925 INFO  - Local ENR: enr:-KG4QG5QP0c22khwuP5l527rdA7k4F8DOTmEvBkU7vKEZbPcYVCHQ_KSUzvzBeg3kgG0IBsfsxXQEWmUI9uLzpekNqQGhGV0aDKQ7nHpc2IAAHH__________4JpZIJ2NIJpcIQUbaj6iXNlY3AyNTZrMaECfG9Kq9me_TPIBTBMUBtN1lV-Snh7YpSs-Tcbedik6aaDdGNwgiMog3VkcIIjKA
consensus_1       | 2022-01-24 02:18:59.245 INFO  - Started ServerConnector@657570f7{HTTP/1.1, (http/1.1)}{0.0.0.0:5052}
consensus_1       | 2022-01-24 02:18:59.245 INFO  - Started @11054ms
consensus_1       | 2022-01-24 02:18:59.246 INFO  - Listening on http://localhost:5052/
consensus_1       | 2022-01-24 02:18:59.246 INFO  - Javalin started in 482ms \o/
consensus_1       | 2022-01-24 02:18:59.254 FATAL - Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       | tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.keystoreInUseException(KeystoreLocker.java:85) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.attemptReplaceStaleLockFile(KeystoreLocker.java:68) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.lockKeystore(KeystoreLocker.java:43) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.loadBLSPrivateKey(LocalValidatorSource.java:267) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.createSigner(LocalValidatorSource.java:254) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource$SlashingProtectedValidatorProvider.createSigner(SlashingProtectedValidatorSource.java:92) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.MultithreadedValidatorLoader.lambda$loadValidators$0(MultithreadedValidatorLoader.java:64) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
consensus_1       | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
consensus_1       | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
consensus_1       | at java.lang.Thread.run(Unknown Source) ~[?:?]
consensus_1       | Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       |
consensus_1       | To display full help:
consensus_1       | teku [COMMAND] --help
consensus_1       | 2022-01-24 02:19:05,199 main INFO Setting logging level to INFO
consensus_1       | 2022-01-24 02:19:06,185 main INFO Configuring logging for destination: console
consensus_1       | 2022-01-24 02:19:06,186 main INFO Logging includes events: true
consensus_1       | 2022-01-24 02:19:06,186 main INFO Logging includes validator duties: true
consensus_1       | 2022-01-24 02:19:06,186 main INFO Logging includes color: true
consensus_1       | 2022-01-24 02:19:06,213 main INFO Include P2P warnings set to: false
consensus_1       | 2022-01-24 02:19:06.216 INFO  - Teku version: teku/v22.1.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
consensus_1       | 2022-01-24 02:19:06.223 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
consensus_1       | 2022-01-24 02:19:06.676 INFO  - validator-api-enabled is false, not starting rest api.
consensus_1       | 2022-01-24 02:19:06.785 INFO  - Using default implementation for ThreadExecutor
consensus_1       | 2022-01-24 02:19:06.786 INFO  - Job execution threads will use class loader of thread: main
consensus_1       | 2022-01-24 02:19:06.833 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
consensus_1       | 2022-01-24 02:19:06.833 INFO  - Quartz Scheduler v.2.3.2 created.
consensus_1       | 2022-01-24 02:19:06.834 INFO  - RAMJobStore initialized.
consensus_1       | 2022-01-24 02:19:06.843 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
consensus_1       |   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
consensus_1       |   NOT STARTED.
consensus_1       |   Currently in standby mode.
consensus_1       |   Number of jobs executed: 0
consensus_1       |   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
consensus_1       |   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
consensus_1       |
consensus_1       | 2022-01-24 02:19:06.843 INFO  - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
consensus_1       | 2022-01-24 02:19:06.843 INFO  - Quartz scheduler version: 2.3.2
consensus_1       | 2022-01-24 02:19:06.986 INFO  - Using optimized BLST library
consensus_1       | 2022-01-24 02:19:06.989 INFO  - Storing beacon chain data in: /var/lib/teku/beacon
consensus_1       | 2022-01-24 02:19:07.011 INFO  - Starting metrics http service on 0.0.0.0:8008
consensus_1       | 2022-01-24 02:19:07.024 INFO  - BLS: loaded BLST library
consensus_1       | 2022-01-24 02:19:07.027 INFO  - Loading 1 validator keys...
consensus_1       | 2022-01-24 02:19:07.312 INFO  - Metrics service started and listening on 8008:8008
consensus_1       | 2022-01-24 02:19:07.315 INFO  - Beacon data directory set to: /var/lib/teku/beacon
consensus_1       | 2022-01-24 02:19:07.399 INFO  - Created leveldb_tree Hot and Finalized database (leveldb-tree) at /var/lib/teku/beacon/db
consensus_1       | 2022-01-24 02:19:07.477 INFO  - Using execution engine at http://execution:8545
consensus_1       | 2022-01-24 02:19:07.544 INFO  - Initializing storage
consensus_1       | 2022-01-24 02:19:10.744 INFO  - Storage initialization complete
consensus_1       | 2022-01-24 02:19:11.789 INFO  - Loading generated p2p private key from: generated-node-key
consensus_1       | 2022-01-24 02:19:12.316 INFO  - PreGenesis Local ENR: enr:-KG4QNevwhBk_piRfa_eF95p12LOvZ9H7Sf3I7iP_i05M5MEPBsv0eb37kAYTKdUQXs5mG3WEfnV-MYZT5Z75FUQvsgIhGV0aDKQmCTRN2AAAGn__________4JpZIJ2NIJpcIQUbaj6iXNlY3AyNTZrMaECfG9Kq9me_TPIBTBMUBtN1lV-Snh7YpSs-Tcbedik6aaDdGNwgiMog3VkcIIjKA
consensus_1       | 2022-01-24 02:19:12.323 INFO  - Using multipeer sync
consensus_1       | 2022-01-24 02:19:12.489 WARN  - JDK15 and Kotlin 1.5 break reflection in different ways - the OpenAPI plugin will not work properly. Please visit https://github.com/tipsy/javalin/issues/1193 if you want to help fix this issue.
consensus_1       | 2022-01-24 02:19:12.539 INFO  - Logging initialized @10531ms to org.eclipse.jetty.util.log.Slf4jLog
consensus_1       | 2022-01-24 02:19:12.761 INFO  - The latest finalized checkpoint at epoch 0 fell outside of the weak subjectivity period after epoch 1157, which is prior to the current epoch 8674.
consensus_1       | 2022-01-24 02:19:12.763 INFO  - The latest finalized checkpoint at epoch 0 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
consensus_1       | 2022-01-24 02:19:12.816 INFO  - Starting libp2p network...
consensus_1       | 2022-01-24 02:19:12.831 INFO  - Listening for connections on: /ip4/20.109.168.250/tcp/9000/p2p/16Uiu2HAm3oQxiapCdorTp8C6ceWoHM9SnPzzCmuRcGgb2muMSmUq
consensus_1       | 2022-01-24 02:19:12.836 INFO  - Starting discovery server on UDP port 9000
consensus_1       | 2022-01-24 02:19:12.854 INFO  - Monitor has started. Waiting MERGE fork activation. Polling every PT14S
consensus_1       | 2022-01-24 02:19:12.856 INFO  - Starting Javalin ...
consensus_1       | 2022-01-24 02:19:12.872 INFO  - UDP discovery client started
consensus_1       | 2022-01-24 02:19:12.907 INFO  - You are running Javalin 4.1.1 (released October 10, 2021. Your Javalin version is 105 days old. Consider upgrading!).
consensus_1       | 2022-01-24 02:19:12.990 INFO  - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 17.0.1+12
consensus_1       | 2022-01-24 02:19:13.038 INFO  - Local ENR: enr:-KG4QOuwLq2mn0TUCgnnzUzRiW8J3XvYwTyseZwdwRPW6bJAVNM9tBJK5Xs6KUcBuaraQ7Q6ppqmuxM4_-78Rl5HAfEJhGV0aDKQ7nHpc2IAAHH__________4JpZIJ2NIJpcIQUbaj6iXNlY3AyNTZrMaECfG9Kq9me_TPIBTBMUBtN1lV-Snh7YpSs-Tcbedik6aaDdGNwgiMog3VkcIIjKA
consensus_1       | 2022-01-24 02:19:13.375 INFO  - Started ServerConnector@657570f7{HTTP/1.1, (http/1.1)}{0.0.0.0:5052}
consensus_1       | 2022-01-24 02:19:13.375 INFO  - Started @11368ms
consensus_1       | 2022-01-24 02:19:13.376 INFO  - Listening on http://localhost:5052/
consensus_1       | 2022-01-24 02:19:13.376 INFO  - Javalin started in 520ms \o/
consensus_1       | 2022-01-24 02:19:13.379 FATAL - Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       | tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.keystoreInUseException(KeystoreLocker.java:85) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.attemptReplaceStaleLockFile(KeystoreLocker.java:68) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.KeystoreLocker.lockKeystore(KeystoreLocker.java:43) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.loadBLSPrivateKey(LocalValidatorSource.java:267) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.createSigner(LocalValidatorSource.java:254) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource$SlashingProtectedValidatorProvider.createSigner(SlashingProtectedValidatorSource.java:92) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at tech.pegasys.teku.validator.client.loader.MultithreadedValidatorLoader.lambda$loadValidators$0(MultithreadedValidatorLoader.java:64) ~[teku-validator-client-22.1.0.jar:22.1.0]
consensus_1       | at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
consensus_1       | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
consensus_1       | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
consensus_1       | at java.lang.Thread.run(Unknown Source) ~[?:?]
consensus_1       | Keystore file /keys/0x8aedb6edd6a724878e164fa56236d2269e1842de3e0fbad0aa572901eaf9dc9cc37ca35222edb4ed3b00ff65ade407e2.json.lock already in use.
consensus_1       |
consensus_1       | To display full help:
consensus_1       | teku [COMMAND] --help
luis@kintsugi-vm:~/eth-docker$
```

**Comment by yorickdowne** [comment]
Interesting. Say more please. What environment is this running in? What's the OS? Is there any NFS/EFS storage behind the docker volumes, or is it all local-attached?

**Comment by yorickdowne** [comment]
That might do it, docker isn’t friendly to symlinks. Try removing docker volumes - you’ll have to reimport keys - remove the symlinks and tell docker that its root is now on the new drive. That’s in a config file and can be googled. From there you are hopefully golden.
